simpleArgs: &simple-args
  _revocation:
    [
      "1.0.0",
      "revReg123",
      "CL_ACCUM",
      "did:indy2:indy_besu:MRDxoJ2Mz3ZuyqaqsjVTdN/anoncreds/v0/CLAIM_DEF/did:indy2:indy_besu:MRDxoJ2Mz3ZuyqaqsjVTdN/anoncreds/v0/SCHEMA/ScoreSch1/1.0",
      "test-tag",
      "value123",
      "did:indy2:indy_besu:MRDxoJ2Mz3ZuyqaqsjVTdN",
    ]

  numberOfAccounts: &number-of-accounts 1
  timeOfTest: &time-of-test 10

test:
  name: createRevocationRegistry Test
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with simple account opening & querying transactions.
  workers:
    number: 1
  rounds:
    - label: createRevocationRegistry
      description: >-
        Test description for the opening of an account through the deployed
        contract.
      txDuration: *time-of-test
      rateControl:
        type: fixed-rate
        opts:
          tps: 120
      workload:
        module: benchmarks/scenario/RevocationRegistry/createRevocationRegistry.js
        arguments: *simple-args

monitors:
  resource:
    - module: prometheus
      options:
        url: "http://NODE1_IP:9545"
        interval: 5
        metrics:
          include: [process_cpu_seconds_total, process_resident_memory_bytes]
    - module: prometheus
      options:
        url: "http://NODE2_IP:9545"
        interval: 5
        metrics:
          include: [process_cpu_seconds_total, process_resident_memory_bytes]

observer:
  type: local
  interval: 5
